users = [
    {
      "resource_id": "divvyuser:291:",
      "name": "Alan Foster",
      "user_id": 291,
      "email_address": "afoster@rapid7.com",
      "username": "afoster@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:224:",
      "name": "Alan Foster",
      "user_id": 224,
      "email_address": "afoster@rapid7.com",
      "username": "afoster",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:292:",
      "name": "Andrew Warnick",
      "user_id": 292,
      "email_address": "awarnick@rapid7.com",
      "username": "awarnick@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:225:",
      "name": "Andrew Warnick",
      "user_id": 225,
      "email_address": "awarnick@rapid7.com",
      "username": "awarnick",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:293:",
      "name": "Antonio Etheridge",
      "user_id": 293,
      "email_address": "aetheridge@rapid7.com",
      "username": "aetheridge@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:226:",
      "name": "Antonio Etheridge",
      "user_id": 226,
      "email_address": "aetheridge@rapid7.com",
      "username": "aetheridge",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:294:",
      "name": "Autumn Stambaugh",
      "user_id": 294,
      "email_address": "astambaugh@rapid7.com",
      "username": "astambaugh@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:227:",
      "name": "Autumn Stambaugh",
      "user_id": 227,
      "email_address": "astambaugh@rapid7.com",
      "username": "astambaugh",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:295:",
      "name": "Ben Garber",
      "user_id": 295,
      "email_address": "bgarber@@rapid7.com",
      "username": "bgarber@@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:228:",
      "name": "Ben Garber",
      "user_id": 228,
      "email_address": "bgarber@@rapid7.com",
      "username": "bgarber",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:195:",
      "name": "Bernard Beirne",
      "user_id": 195,
      "email_address": "bernard_beirne@rapid7.com",
      "username": "bbeirne@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "last_login_time": "2020-12-01 18:22:19",
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:296:",
      "name": "Billy Cannon",
      "user_id": 296,
      "email_address": "bcannon@rapid7.com",
      "username": "bcannon@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:229:",
      "name": "Billy Cannon",
      "user_id": 229,
      "email_address": "bcannon@rapid7.com",
      "username": "bcannon",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:297:",
      "name": "Brendan Laws",
      "user_id": 297,
      "email_address": "blaws@rapid7.com",
      "username": "blaws@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:230:",
      "name": "Brendan Laws",
      "user_id": 230,
      "email_address": "blaws@rapid7.com",
      "username": "blaws",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:298:",
      "name": "Charlotte Rees",
      "user_id": 298,
      "email_address": "crees@rapid7.com",
      "username": "crees@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:231:",
      "name": "Charlotte Rees",
      "user_id": 231,
      "email_address": "crees@rapid7.com",
      "username": "crees",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:299:",
      "name": "Daniel Prauser",
      "user_id": 299,
      "email_address": "dprauser@rapid7.com",
      "username": "dprauser@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:232:",
      "name": "Daniel Prauser",
      "user_id": 232,
      "email_address": "dprauser@rapid7.com",
      "username": "dprauser",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:300:",
      "name": "David Bosquet",
      "user_id": 300,
      "email_address": "dbosquet@rapid7.com",
      "username": "dbosquet@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:233:",
      "name": "David Bosquet",
      "user_id": 233,
      "email_address": "dbosquet@rapid7.com",
      "username": "dbosquet",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:301:",
      "name": "David Coleman",
      "user_id": 301,
      "email_address": "dcoleman@rapid7.com",
      "username": "dcoleman@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:234:",
      "name": "David Coleman",
      "user_id": 234,
      "email_address": "dcoleman@rapid7.com",
      "username": "dcoleman",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:302:",
      "name": "David Howe",
      "user_id": 302,
      "email_address": "dhowe@rapid7.com",
      "username": "dhowe@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:235:",
      "name": "David Howe",
      "user_id": 235,
      "email_address": "dhowe@rapid7.com",
      "username": "dhowe",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:213:",
      "name": "David Howorth",
      "user_id": 213,
      "email_address": "david_howorth@rapid7.com",
      "username": "david_howorth@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "last_login_time": "2020-12-08 13:59:40",
      "navigation_blacklist": [],
    },
    {
      "resource_id": "divvyuser:303:",
      "name": "Denis Podgurskiy",
      "user_id": 303,
      "email_address": "dpodgurskiy@rapid7.com",
      "username": "dpodgurskiy@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:236:",
      "name": "Denis Podgurskiy",
      "user_id": 236,
      "email_address": "dpodgurskiy@rapid7.com",
      "username": "dpodgurskiy",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:304:",
      "name": "Dondi Simon",
      "user_id": 304,
      "email_address": "dsimon@rapid7.com",
      "username": "dsimon@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:237:",
      "name": "Dondi Simon",
      "user_id": 237,
      "email_address": "dsimon@rapid7.com",
      "username": "dsimon",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:305:",
      "name": "Eric Wilson",
      "user_id": 305,
      "email_address": "ewilson@rapid7.com",
      "username": "ewilson@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:238:",
      "name": "Eric Wilson",
      "user_id": 238,
      "email_address": "ewilson@rapid7.com",
      "username": "ewilson",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:306:",
      "name": "Erik Burns",
      "user_id": 306,
      "email_address": "eburns@rapid7.com",
      "username": "eburns@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:239:",
      "name": "Erik Burns",
      "user_id": 239,
      "email_address": "eburns@rapid7.com",
      "username": "eburns",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:201:",
      "name": "Evan Enriquez",
      "user_id": 201,
      "email_address": "eenriquez@rapid7.com",
      "username": "eenriquez@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:240:",
      "name": "Evan Enriquez",
      "user_id": 240,
      "email_address": "eenriquez@rapid7.com",
      "username": "eenriquez",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:307:",
      "name": "Felipe Legorreta",
      "user_id": 307,
      "email_address": "flegorreta@rapid7.com",
      "username": "flegorreta@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:241:",
      "name": "Felipe Legorreta",
      "user_id": 241,
      "email_address": "flegorreta@rapid7.com",
      "username": "flegorreta",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:194:",
      "name": "Gary Silverman",
      "user_id": 194,
      "email_address": "gary_silverman@rapid7.com",
      "username": "gsilverman@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "last_login_time": "2020-11-25 18:33:46",
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:308:",
      "name": "Giovanni Ruberto",
      "user_id": 308,
      "email_address": "gruberto@rapid7.com",
      "username": "gruberto@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:242:",
      "name": "Giovanni Ruberto",
      "user_id": 242,
      "email_address": "gruberto@rapid7.com",
      "username": "gruberto",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:309:",
      "name": "Graem McMillan",
      "user_id": 309,
      "email_address": "gmcmillan@rapid7.com",
      "username": "gmcmillan@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:243:",
      "name": "Graem McMillan",
      "user_id": 243,
      "email_address": "gmcmillan@rapid7.com",
      "username": "gmcmillan",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:310:",
      "name": "Greg Overton",
      "user_id": 310,
      "email_address": "goverton@rapid7.com",
      "username": "goverton@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:244:",
      "name": "Greg Overton",
      "user_id": 244,
      "email_address": "goverton@rapid7.com",
      "username": "goverton",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:311:",
      "name": "Hanna Coakley",
      "user_id": 311,
      "email_address": "hcoakley@rapid7.com",
      "username": "hcoakley@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:245:",
      "name": "Hanna Coakley",
      "user_id": 245,
      "email_address": "hcoakley@rapid7.com",
      "username": "hcoakley",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:187:",
      "name": "Hollis Howell",
      "user_id": 187,
      "email_address": "Hollis_Howell@rapid7.com",
      "username": "hollis.howell",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
    },
    {
      "resource_id": "divvyuser:312:",
      "name": "Ivan Lee",
      "user_id": 312,
      "email_address": "ilee@rapid7.com",
      "username": "ilee@rapid7.com",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    },
    {
      "resource_id": "divvyuser:246:",
      "name": "Ivan Lee",
      "user_id": 246,
      "email_address": "ilee@rapid7.com",
      "username": "ilee",
      "organization_name": "Rapid7",
      "organization_id": 20,
      "groups": 0,
      "owned_resources": 0,
      "consecutive_failed_login_attempts": 0,
      "navigation_blacklist": [],
      "server_name": "okta",
    }
  ]



for user in users:
    if user['username']:
        try:
            if user['server_name'] == "okta":
                print(user['user_id'])
        except Exception:
            print("")